### ISSUE TITLE
Add option to re-run tests with --failed

### ISSUE THREAD

**Issue by embray** [sagemath/sage-patchbot#105]
Often times a test run will leave me with one or two superficial, transient test failures.  Most of the time it's a timeout caused, for example, by the system being under additional load at the time the test was run.

It would be nice if the patchbot had an option (if not the default) to re-run the tests with the `--failed` option and report success if that passes.

Of course, this can in principle mask real failures that might have some dependence on the order in which the tests were run.  But cases where test ordering matters is somewhat non-deterministic in the first place, so I don't think this is more or less bad.

**Comment by embray** [comment]
(P.S. happy to make a PR if this is a good idea)

**Comment by embray** [comment]
Fixed by #107.

**Comment by koffie** [comment]
Hi, 

I just looked into this and what the code right now seems to does is retry up to N times until it passes. I think it would be better if it did "retry N times, and only pass if it passes all N times".

Right now this just seems to be made to suppress honest failures. What are your thoughts on this?

**Comment by embray** [comment]
If you look at the description of the ticket, what you describe would be counter to the purpose of this feature which is to retry only those tests that failed on the initial test run, in order to catch transient failures.    It's true that this can hypothetically suppress honest failures in odd cases where a test fails the first time consistently, but I think this should be checked for with occasional manual investigation.

**Comment by koffie** [comment]
Ok, reading back my previous comment I maybe was not clear enough with what I meant. My goal is also to suppress transient failures.
What I want the behaviour to be is:

First test one time, if this passes, no retries are done.
If first test fails retry N times.
If one of the retries fails again the bug is not transient so report it as actual bug.
If all retries pass then consider it transient and report it as passed on retry.

The main advantage with respect to the current behavior is that the current behaviour calls a bug transient if its change of **not** occuring is around 1/N, while I would like to call it transient if its chance of occuring is around 1/N. 

Since if some non deterministic code fails one out of every 10 times I would not call that transient.

**Comment by embray** [comment]
I see what you're saying, that makes sense.  I think a separate issue should be opened though.  I'm not motivated enough right now to do anything about it but I agree with what you're saying.

**Comment by embray** [comment]
Hmm...one thing that will make this difficult is that this currently relies on behavior of the sage test runner that it will retry failed tests only, but if you retry N times and all the tests succeed on the first try then it won't run any tests on subsequent retries, I think.
